### ISSUE TITLE
Source code / license?

### ISSUE THREAD

**Issue by lgierth** [TRON-US/btfs-binary-releases#9]
This looks like a modified go-ipfs. Where can I find the source code so that I can see the differences from IPFS?

**Comment by jin-tron** [comment]
By end of June, you will see it.

**Comment by whyrusleeping** [comment]
Where is the license at?

**Comment by jin-tron** [comment]
Please refer https://github.com/ipfs/go-ipfs

**Comment by whyrusleeping** [comment]
Thats... not how licenses work.

**Comment by whyrusleeping** [comment]
In the MIT license:

> The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

And one of the many relevant statements in the Apache License:

> You must give any other recipients of the Work or Derivative Works a copy of this License
